#SimuProc 1.4.2.0
; RICARDO MUÑOZ BOLAÑOS
; 21331272
; EL FACTORIAL
MSG EXPERIMENTO FACTORIAL ;0X0
LDT INGRESA N (UN ENTERO); Y LO PONDRÁ EN AX (0X1)
STA 015; GUARDO EL NUUMERO EN LA MEMORIA
MOV CX,AX; ESTABLEZCO EL INICIO DEL LOOP
MSG ********
EAP ; MUESTRA CONTENIDO DE AX
DEC 015
MUL 015
LOOP 04
MSG EL FACTORIAL ES:
EAP
HLT
; LOOP
; DECREMENTA CX
; REVISA SI CX = 0
; SI NO ES CERO, CONTINUA EL FLUJO EN UNA DIRECCIÓN ESPECIFICADA

