#SimuProc 1.4.2.0
; RICARDO MUÑOZ BOLAÑOS
; 21331272
; FACTORIAL
MSG ESTE PROGRAMA CALCULARÁ EL FACTORIAL DESDE 1 HASTA N
LDT INGRESA N (UN ENTERO)
MOV CX,AX
MOV AX,0D
MUL 0D
INC 0D
MSG ********
EAP
LOOP 04
MSG EL FACTORIAL ES:
EAP
MOV 0D,0E
HLT
#0D
0001
#0E
0001
; LOOP
; DECREMENTA CX
; REVISA SI CX = 0
; SI NO ES CERO, CONTINUA EL FLUJO EN UNA DIRECCIÓN ESPECIFICADA
; ESTE PROGRAMA PUEDE EJECUTARSE MÁS DE UNA VEZ
; SIN NECESIDAD DE AJUSTES EN EL SIMULADOR

