#SimuProc 1.4.2.0
;PROGRAMA HECHO POR MBR
;MARTES 6 DE FEBRERO DE 2024 A LAS 16:53
MSG SUMA DE TRES NÚMEROS
LDT INGRESE EL PRIMER NÚMERO
STA 010 ;PONE LOS DATOS EN 010
LDT INGRESE EL SEGUNDO NÚMERO
ADD 010 ;LA SUMA PONE EL RESULTADO EN AX
STA 011
LDT INGRESE EL ÚLTIMO NÚMERO ; LO CAPTURA EN AX
ADD 011
MSG LA SUMA DE DOS NÚMEROS ES:
EAP
HLT
; SE DEBE TENER PRECAUCIÓN PORQUE
; AX SIEMPRE SE SOBREESCRIBE
