#SimuProc 1.4.2.0
; RICARDO MUÑOZ BOLAÑOS
; 21331272
MSG PROGRAMA CON MENÚ
MSG 1) SUMA
MSG 2) RESTA
MSG 3) MULTIPLICACIÓN
MSG 4) DIVISIÓN
LDT ELIGE UNA OPCIÓN
CMP 3A
JEQ 0F
CMP 3B
JEQ 19
CMP 3C
JEQ 23
CMP 3D
JEQ 2D
JMP 37
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
MSG USTED ELIGIÓ SUMA
MSG DAME EL PRIMER NÚMERO
IN AX,1
STF 3E
MSG DAME EL SEGUNDO NÚMERO
IN AX,1
ADDF 3E
MSG EL RESULTADO ES
OUT 1,AX
JMP 38
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
MSG USTED ELIGIÓ RESTA
MSG DAME EL PRIMER NÚMERO
IN AX,1
STF 3E
MSG DAME EL SEGUNDO NÚMERO
IN AX,1
SUBF 3E
MSG EL RESULTADO ES
OUT 1,AX
JMP 38
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
MSG USTED ELIGIÓ MULTIPLICACIÓN
MSG DAME EL PRIMER NÚMERO
IN AX,1
STF 3E
MSG DAME EL SEGUNDO NÚMERO
IN AX,1
MULF 3E
MSG EL RESULTADO ES
OUT 1,AX
JMP 38
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
MSG USTED ELIGIÓ DIVISIÓN
MSG DAME EL PRIMER NÚMERO
IN AX,1
STF 3E
MSG DAME EL SEGUNDO NÚMERO
IN AX,1
DIVF 3E
MSG EL RESULTADO ES
OUT 1,AX
JMP 38
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
MSG OPCIÓN EQUIVOCADA
MSG GRACIAS POR USAR EL PROGRAMA :)
HLT
#03A
0001
#03B
0010
#03C
0011
#03D
0100
; GUARDA UN NÚMERO ENTERO EN AX
; 34h

