#SimuProc 1.4.2.0
MSG CALCULA EL PROMEDIO DE 3 NUMEROS
LDT DAME EL PRIMER NÚMERO
STA 010
LDT DAME EL SEGUNDO NÚMERO
ADD 010
STA 011
LDT DAME EL TERCER NÚMERO
ADD 011
DIV 012 ;DIVIDE ENTRE LO QUE HAY EN 012
; Y EL RESULTADO LO PONE EN AX
MSG EL RESULTADO ES
EAP
HLT
;VAMOS A CARGAR UN 3 EN LA MEMORIA 012
;LAS COSAS QUE EMPIEZAN CON # NO DEBEN TENER INDENTACIÓN
#012
0011
