#SimuProc 1.4.2.0
; RICARDO MUÑOZ BOLAÑOS
; 21331272
; SUMATORIA DESCENDENTE
MSG ESTE PROGRAMA CALCULARÁ LA SUMATORIA DESDE 0 HASTA N ;0X0
LDT INGRESA N (UN ENTERO); Y LO PONDRÁ EN AX (0X1)
STA 01A
MOV CX,AX
DEC 01A
ADD 01A
MSG ********
EAP
LOOP 04
MSG LA SUMATORIA ES:
EAP
HLT
#01B
0001
; LOOP
; DECREMENTA CX
; REVISA SI CX = 0
; SI NO ES CERO, CONTINUA EL FLUJO EN UNA DIRECCIÓN ESPECIFICADA

