#SimuProc 1.4.2.0
; RICARDO MUÑOZ BOLAÑOS
; 21331272
; SUMATORIA ASCENDENTE
MSG ESTE PROGRAMA CALCULARÁ LA SUMATORIA DESDE 0 HASTA N ;0X0
LDT INGRESA N (UN ENTERO); Y LO PONDRÁ EN AX (0X1)
MOV CX,AX
XOR AX,AX ; LIMPIA EL REGISTRO AX (EN VEZ DE CLA)
ADD 01A ; EL APUNTADOR DEL LOOP DEBE REGRESAR AQUÍ (0X5)
INC 01A
MSG ********
EAP
LOOP 04
MSG LA SUMATORIA ES:
EAP
HLT
#01A
0001
; LOOP
; DECREMENTA CX
; REVISA SI CX = 0
; SI NO ES CERO, CONTINUA EL FLUJO EN UNA DIRECCIÓN ESPECIFICADA

